version: '2'
services:
    changeappserver-app:
        image: changeappserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://changeappserver-mysql:3306/changeappserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    changeappserver-mysql:
        extends:
            file: mysql.yml
            service: changeappserver-mysql
